import { randomUUID } from "crypto"
import { generateText, generateObject } from "ai"
import { getDb } from "@/lib/mongodb"
import type { TaskDoc } from "@/lib/tasks"
import { BLOG_POST_SYSTEM, buildBlogPostPrompt, type BlogPostBrief } from "./prompts/blog-post"
import { TAGLINE_SYSTEM, buildTaglinePrompt, parseTaglines, type TaglineBrief } from "./prompts/taglines"
import { socialMediaSchema, buildSocialMediaSystem, buildSocialMediaPrompt, platformSpec, type SocialMediaBrief } from "./prompts/social-media"
import { LANDING_PAGE_SYSTEM, buildLandingPagePrompt, type LandingPageBrief } from "./prompts/landing-page"
import { CASE_STUDY_SYSTEM, CASE_STUDY_TEMPERATURE, buildCaseStudyPrompt, type CaseStudyBrief } from "./prompts/case-study"
import { BATTLECARD_SYSTEM, buildBattlecardPrompt, type BattlecardBrief } from "./prompts/battlecard"
import { resolveCompetitorTarget } from "./competitive-intel"
import { fetchPageText } from "./serper"
import { getBrandProfile, toPromptInputs } from "./brand-profile"

// ---------------------------------------------------------------------------
// Writer agent — generate_content task handler.
// See migration.md §4 (Writer agent) and §5 Phase 1/3.
// ---------------------------------------------------------------------------

export type ContentMode = "blog_post" | "taglines" | "social_media" | "landing_page" | "case_study" | "battlecard"

export type ScorecardBreakdownItem = {
  criterion: string
  met: boolean
  note: string
}

export type ContentDoc = {
  _id?: string
  contentId: string
  userId: string
  mode: ContentMode
  topic: string
  body: string
  // Set instead of (or alongside) body for list-shaped modes like taglines.
  items?: string[]
  // Persisted for blog_post so the orchestrator can fold fix guidance into a
  // regeneration request (migration.md §5 Phase 4) without losing the
  // original ask.
  brief?: string
  // Set when this draft is an orchestrator-triggered rewrite of a lower-
  // scoring earlier draft.
  regeneratedFrom?: string
  // Set after a regenerated draft is scored — whether the rewrite actually
  // beat the score it was regenerating away from (a rewrite can fix every
  // flagged issue and still score lower by introducing new problems).
  regenerationOutcome?: "improved" | "regressed" | "unchanged"
  previousScore?: number
  // Mode-specific structured context the evaluator needs at scoring time
  // (e.g. landing_page's exact CTA text, case_study's source facts) that
  // doesn't fit the generic topic/brief/body shape.
  meta?: Record<string, string>
  status: "draft" | "published" | "archived"
  // "uploaded" for content brought in for review rather than written by
  // Quill's own writer agent — scoring a piece Quill itself just wrote is a
  // weaker test of the Scorecard than scoring something written elsewhere.
  // Absent (treated as "generated") for every draft created before this
  // field existed. Uploaded content is never auto-regenerated by the
  // orchestrator (lib/agents/index.ts) — rewriting someone else's work
  // without being asked isn't what "review" means.
  origin?: "generated" | "uploaded"
  sourceTaskId: string
  // Populated by the evaluator agent's score_content task (migration.md §5 Phase 2).
  // Absent until scoring runs.
  grade?: "A" | "B" | "C" | "D" | "F"
  score?: number
  breakdown?: ScorecardBreakdownItem[]
  fixGuidance?: string[]
  // Soft, non-graded voice/word-choice observations (content-scorecard.ts) —
  // craft feedback, never factored into score or grade.
  styleNotes?: string[]
  scoredAt?: Date
  createdAt: Date
  updatedAt: Date
}

// Adding a new content mode = one entry here + one prompt file. This is the
// extraction point migration.md §5 Phase 3 grows: one Skribil mode at a time.

export type BattlecardPayload = {
  competitor: string // name or URL, resolved the same way as fetch_competitor_content
  positioning: string
  ourAdvantages?: string
  tone?: string
  style?: string
  mood?: string
}

type GenerateContentPayload =
  | (BlogPostBrief & { mode?: "blog_post"; regeneratedFrom?: string })
  | (TaglineBrief & { mode: "taglines" })
  | (SocialMediaBrief & { mode: "social_media" })
  | (LandingPageBrief & { mode: "landing_page" })
  | (CaseStudyBrief & { mode: "case_study" })
  | (BattlecardPayload & { mode: "battlecard" })

export async function generateContent(task: TaskDoc): Promise<Record<string, unknown>> {
  const payload = task.payload as GenerateContentPayload
  const mode: ContentMode = payload.mode ?? "blog_post"

  let topic: string
  let body: string
  let items: string[] | undefined
  let brief: string | undefined
  let regeneratedFrom: string | undefined
  let meta: Record<string, string> | undefined

  // Real brand profile (migration.md §5 Phase 5 retrieval layer) fills in
  // writingStyle/brandVoice/messaging for every mode below when the caller
  // didn't already supply them explicitly — explicit payload values win.
  // Fetched once per task rather than per-mode; taglines is deliberately
  // excluded (not a mode used for real brand work, per user direction).
  const profile = mode === "taglines" ? null : await getBrandProfile(task.userId)
  const profileInputs = toPromptInputs(profile)

  if (mode === "blog_post") {
    const { topic: t, regeneratedFrom: regenFrom, ...rest } = payload as BlogPostBrief & { regeneratedFrom?: string }
    if (!t || typeof t !== "string") {
      throw new Error("blog_post mode requires a non-empty 'topic' in payload")
    }
    topic = t
    brief = rest.brief
    regeneratedFrom = regenFrom

    const { text } = await generateText({
      model: "anthropic/claude-sonnet-5",
      system: BLOG_POST_SYSTEM,
      prompt: buildBlogPostPrompt({
        topic,
        ...rest,
        writingStyle: rest.writingStyle ?? profileInputs.writingStyle,
        brandVoice: rest.brandVoice ?? profileInputs.brandVoice,
        messaging: rest.messaging ?? profileInputs.messaging,
      }),
      maxOutputTokens: 6000,
      temperature: 0.3,
    })
    body = text
  } else if (mode === "taglines") {
    const { businessName, description, numOptions } = payload as TaglineBrief
    if (!businessName || !description) {
      throw new Error("taglines mode requires 'businessName' and 'description' in payload")
    }
    topic = businessName

    const { text } = await generateText({
      model: "anthropic/claude-sonnet-5",
      system: TAGLINE_SYSTEM,
      prompt: buildTaglinePrompt({ businessName, description }),
      maxOutputTokens: 2000,
      temperature: 0.7,
    })
    items = parseTaglines(text, numOptions)
    body = items.map((line, i) => `${i + 1}. ${line}`).join("\n")
  } else if (mode === "social_media") {
    const socialInput = payload as SocialMediaBrief
    if (!socialInput.content || typeof socialInput.content !== "string") {
      throw new Error("social_media mode requires non-empty 'content' in payload")
    }
    const platform = socialInput.platform ?? "linkedin"
    topic = `${platform} post`

    const { object } = await generateObject({
      model: "anthropic/claude-sonnet-5",
      schema: socialMediaSchema,
      system: buildSocialMediaSystem(platform),
      prompt: buildSocialMediaPrompt({
        ...socialInput,
        writingStyle: socialInput.writingStyle ?? profileInputs.writingStyle,
        brandVoice: socialInput.brandVoice ?? profileInputs.brandVoice,
        messaging: socialInput.messaging ?? profileInputs.messaging,
      }),
      maxOutputTokens: platformSpec(platform).maxOutputTokens,
      temperature: 0.8,
    })
    items = object.posts
    body = items.map((line, i) => `${i + 1}. ${line}`).join("\n\n")
  } else if (mode === "landing_page") {
    const { regeneratedFrom: landingRegenFrom, ...landingInput } = payload as LandingPageBrief & { regeneratedFrom?: string }
    if (!landingInput.title || !landingInput.callToAction) {
      throw new Error("landing_page mode requires 'title' and 'callToAction' in payload")
    }
    topic = landingInput.title
    regeneratedFrom = landingRegenFrom
    meta = {
      callToAction: landingInput.callToAction,
      // Full original payload, for the orchestrator to reconstruct a
      // regeneration request (migration.md §5 Phase 4 extension) without
      // losing structured fields (bullets, goal) that don't fit elsewhere.
      originalPayload: JSON.stringify({
        title: landingInput.title,
        goal: landingInput.goal,
        callToAction: landingInput.callToAction,
        bullets: landingInput.bullets,
        additionalDetails: landingInput.additionalDetails,
      }),
    }

    const { text } = await generateText({
      model: "anthropic/claude-sonnet-5",
      system: LANDING_PAGE_SYSTEM,
      prompt: buildLandingPagePrompt({
        ...landingInput,
        writingStyle: landingInput.writingStyle ?? profileInputs.writingStyle,
        brandVoice: landingInput.brandVoice ?? profileInputs.brandVoice,
        messaging: landingInput.messaging ?? profileInputs.messaging,
      }),
      maxOutputTokens: 2000,
      temperature: 0.3,
    })
    body = text
  } else if (mode === "case_study") {
    const { regeneratedFrom: caseRegenFrom, ...caseInput } = payload as CaseStudyBrief & { regeneratedFrom?: string }
    if (!caseInput.customerName || !caseInput.problem || !caseInput.solution || !caseInput.results) {
      throw new Error("case_study mode requires 'customerName', 'problem', 'solution', and 'results' in payload")
    }
    topic = `${caseInput.customerName} case study`
    regeneratedFrom = caseRegenFrom
    meta = {
      sourceFacts: [
        `Customer: ${caseInput.customerName}`,
        `Role: ${caseInput.customerRole}`,
        caseInput.company ? `Company: ${caseInput.company}` : "",
        `Problem: ${caseInput.problem}`,
        `Solution: ${caseInput.solution}`,
        `Results: ${caseInput.results}`,
        caseInput.quote ? `Quote: "${caseInput.quote}"${caseInput.quoteSpeaker ? ` — ${caseInput.quoteSpeaker}` : ""}` : "",
      ].filter(Boolean).join("\n"),
      // Full original payload, for the orchestrator to reconstruct a
      // regeneration request with the exact same facts (migration.md §5
      // Phase 4 extension) — a case study regeneration must never let the
      // facts drift, only the prose/tone around them.
      originalPayload: JSON.stringify({
        customerName: caseInput.customerName,
        customerRole: caseInput.customerRole,
        company: caseInput.company,
        problem: caseInput.problem,
        solution: caseInput.solution,
        results: caseInput.results,
        quote: caseInput.quote,
        quoteSpeaker: caseInput.quoteSpeaker,
      }),
    }

    const { text } = await generateText({
      model: "anthropic/claude-sonnet-5",
      system: CASE_STUDY_SYSTEM,
      prompt: buildCaseStudyPrompt({
        ...caseInput,
        writingStyle: caseInput.writingStyle ?? profileInputs.writingStyle,
        brandVoice: caseInput.brandVoice ?? profileInputs.brandVoice,
        messaging: caseInput.messaging ?? profileInputs.messaging,
      }),
      maxOutputTokens: 2000,
      temperature: CASE_STUDY_TEMPERATURE,
    })
    body = text
  } else if (mode === "battlecard") {
    const battlecardInput = payload as BattlecardPayload
    if (!battlecardInput.competitor || !battlecardInput.positioning) {
      throw new Error("battlecard mode requires 'competitor' and 'positioning' in payload")
    }

    const target = await resolveCompetitorTarget(battlecardInput.competitor)
    const pageText = await fetchPageText(target.url)
    if (!pageText || pageText.length < 200) {
      throw new Error(`Could not read enough content from ${target.url} to ground a battlecard (likely JS-rendered or blocked)`)
    }

    topic = `${target.name} battlecard`
    meta = { competitorUrl: target.url }

    const { text } = await generateText({
      model: "anthropic/claude-sonnet-5",
      system: BATTLECARD_SYSTEM,
      prompt: buildBattlecardPrompt({
        competitorName: target.name,
        competitorPageText: pageText,
        positioning: battlecardInput.positioning,
        ourAdvantages: battlecardInput.ourAdvantages,
        tone: battlecardInput.tone,
        style: battlecardInput.style,
        mood: battlecardInput.mood,
        writingStyle: profileInputs.writingStyle,
        brandVoice: profileInputs.brandVoice,
        messaging: profileInputs.messaging,
      }),
      maxOutputTokens: 4000,
      temperature: 0.4,
    })
    body = text
  } else {
    throw new Error(`Unknown content mode: ${mode}`)
  }

  // The model occasionally returns an empty response (observed live during
  // regeneration testing) with no error — nothing upstream catches that, so
  // an empty draft would otherwise persist as a normal "done" ContentDoc and
  // silently score 0/F later. Treat it as a real task failure instead, so
  // the existing retry-with-backoff logic (lib/tasks.ts) handles it.
  const hasEmptyOutput = items ? items.length === 0 : !body || body.trim().length === 0
  if (hasEmptyOutput) {
    throw new Error(`${mode} generation returned no content — the model returned an empty response`)
  }

  const db = await getDb()
  const contentId = randomUUID()
  const now = new Date()

  await db.collection<ContentDoc>("content").insertOne({
    contentId,
    userId: task.userId,
    mode,
    topic,
    body,
    ...(items ? { items } : {}),
    ...(brief ? { brief } : {}),
    ...(regeneratedFrom ? { regeneratedFrom } : {}),
    ...(meta ? { meta } : {}),
    status: "draft",
    sourceTaskId: task.taskId,
    createdAt: now,
    updatedAt: now,
  })

  return {
    contentId,
    mode,
    topic,
    ...(items ? { itemCount: items.length } : { wordCount: body.trim().split(/\s+/).length }),
  }
}
